### PR TITLE
Improve handling of FLT accurary errors

### PR DESCRIPTION
**Pull request by mcara**
Fixes issue not completely fixed in #58

JWST regression test: https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/1363

### CODE REVIEW

**Comment by jhunkeler** [comment]
I went through the code and found a couple things.

* `populate1DHist_` always returns `1`
* `populate1DHist` might return `NULL` _or_ `1`
  * What does `NULL` translate to on the interpreter side? `None` or `0`?
  * Do you think it'd be better to initialize `status = 0` at the start of the function, and then return `Py_BuildValue("i", status);` everywhere instead of `NULL`?

**Comment by mcara** [comment]
> `populate1DHist_` always returns 1

Not my fault but I am not going to change it here (in this PR) because that is a change in API. This PR is just a bug fix. it will be a part of a future PR that will improve the overall code.

> What does NULL translate to on the interpreter side? None or 0? ...

**Comment by mcara** [comment]
> `populate1DHist_` always returns 1

Not my fault but I am not going to change it here (in this PR) because that is a change in API. This PR is just a bug fix. it will be a part of a future PR that will improve the overall code.

> What does NULL translate to on the interpreter side? None or 0? ...

`NULL` signals that function resulted in an error. It will raise an exception on Python side. No need to initialize to 0 if it can never happen.

**Comment by mcara** [comment]
returning 0 will not raise an exception

**Comment by jhunkeler** [comment]
> NULL signals that function resulted in an error. It will raise an exception on Python side. (see, e.g., https://docs.python.org/3/extending/extending.html#back-to-the-example) No need to initialize to 0 if it can never happen.

Thanks for the clarification. I wasn't aware that returning `NULL` automatically raises an exception by itself.

**Review by jhunkeler — APPROVED** [review]

**Pull request merged**
